### ISSUE TITLE
Error traceback running have a look!

### ISSUE THREAD

**Issue by faisalrathore93** [robre/jsmon#4]
Traceback (most recent call last):
  File "jsmon.py", line 144, in <module>
    main()        
  File "jsmon.py", line 132, in main
    ep_text = get_endpoint(ep)
  File "jsmon.py", line 42, in get_endpoint
    r = requests.get(endpoint)
  File "/home/faisal/.local/lib/python3.8/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/faisal/.local/lib/python3.8/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/faisal/.local/lib/python3.8/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/faisal/.local/lib/python3.8/site-packages/requests/sessions.py", line 427, in prepare_request
    p.prepare(
  File "/home/faisal/.local/lib/python3.8/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/faisal/.local/lib/python3.8/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '# Ignore everything in this directory': No schema supplied. Perhaps you meant http://# Ignore everything in this directory?

what is this? how to fix it? i am running it on my laptop having ubuntu 20.04

**Comment by maverickNerd** [comment]
Go to targets directory and delete .gitignore file, and then run jsmon.py, this error will not come then.

**Comment by yassineaboukir** [comment]
Clone the new version which should resolve this issue.
